package com.apps.pu.hibah.entity;
// Generated 08-Apr-2018 12:48:59 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Barang generated by hbm2java
 */
@Entity
@Table(name = "barang", catalog = "hibah")
public class Barang implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idBarang;
	private String kodeBarang;
	private String namaBarang;
	private Date updateDate;
	private String updateBy;
	private Date createDate;
	private String createBy;

	public Barang() {
	}

	public Barang(String kodeBarang, String namaBarang, Date updateDate, String updateBy, Date createDate,
			String createBy) {
		this.kodeBarang = kodeBarang;
		this.namaBarang = namaBarang;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.createDate = createDate;
		this.createBy = createBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_barang", unique = true, nullable = false)
	public Integer getIdBarang() {
		return this.idBarang;
	}

	public void setIdBarang(Integer idBarang) {
		this.idBarang = idBarang;
	}

	@Column(name = "kode_barang", nullable = false, length = 100)
	public String getKodeBarang() {
		return this.kodeBarang;
	}

	public void setKodeBarang(String kodeBarang) {
		this.kodeBarang = kodeBarang;
	}

	@Column(name = "nama_barang", nullable = false, length = 500)
	public String getNamaBarang() {
		return this.namaBarang;
	}

	public void setNamaBarang(String namaBarang) {
		this.namaBarang = namaBarang;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "update_by", nullable = false, length = 45)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "create_by", nullable = false, length = 45)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

}
