package com.apps.pu.hibah.entity;
// Generated 08-Apr-2018 12:48:59 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Direktorat generated by hbm2java
 */
@Entity
@Table(name = "direktorat", catalog = "hibah", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Direktorat implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idDirektorat;
	private String name;
	private String desc;
	private Date updateDate;
	private String updateBy;
	private Date createDate;
	private String createBy;
	private Set<Satker> satkers = new HashSet<Satker>(0);

	public Direktorat() {
	}

	public Direktorat(String name, Date updateDate, String updateBy, Date createDate, String createBy) {
		this.name = name;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.createDate = createDate;
		this.createBy = createBy;
	}

	public Direktorat(String name, String desc, Date updateDate, String updateBy, Date createDate, String createBy,
			Set<Satker> satkers) {
		this.name = name;
		this.desc = desc;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.createDate = createDate;
		this.createBy = createBy;
		this.satkers = satkers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_direktorat", unique = true, nullable = false)
	public Integer getIdDirektorat() {
		return this.idDirektorat;
	}

	public void setIdDirektorat(Integer idDirektorat) {
		this.idDirektorat = idDirektorat;
	}

	@Column(name = "name", unique = true, nullable = false, length = 1000)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "desc", length = 1000)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "update_by", nullable = false, length = 100)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "create_by", nullable = false, length = 100)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "direktorat")
	public Set<Satker> getSatkers() {
		return this.satkers;
	}

	public void setSatkers(Set<Satker> satkers) {
		this.satkers = satkers;
	}

}
