package com.apps.pu.hibah.entity;
// Generated 04-Feb-2018 21:45:47 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RoleUser generated by hbm2java
 */
@Entity
@Table(name = "role_user", catalog = "hibah")
public class RoleUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idRoleUser;
	private Roles roles;
	private Users users;
	private Date updateDate;
	private String updateBy;
	private Date createDate;
	private String createBy;

	public RoleUser() {
	}

	public RoleUser(Date updateDate, String updateBy, Date createDate, String createBy) {
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.createDate = createDate;
		this.createBy = createBy;
	}

	public RoleUser(Roles roles, Users users, Date updateDate, String updateBy, Date createDate, String createBy) {
		this.roles = roles;
		this.users = users;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.createDate = createDate;
		this.createBy = createBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_role_user", unique = true, nullable = false)
	public Integer getIdRoleUser() {
		return this.idRoleUser;
	}

	public void setIdRoleUser(Integer idRoleUser) {
		this.idRoleUser = idRoleUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_role")
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_user")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "update_by", nullable = false, length = 45)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "create_by", nullable = false, length = 45)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

}
