package com.apps.pu.hibah.entity;
// Generated 08-Apr-2018 12:48:59 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Satker generated by hbm2java
 */
@Entity
@Table(name = "satker", catalog = "hibah", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Satker implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idSatker;
	private Direktorat direktorat;
	private String name;
	private String desc;
	private Date updateDate;
	private String updateBy;
	private Date createDate;
	private String createBy;

	public Satker() {
	}

	public Satker(Direktorat direktorat, String name, Date updateDate, String updateBy, Date createDate,
			String createBy) {
		this.direktorat = direktorat;
		this.name = name;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.createDate = createDate;
		this.createBy = createBy;
	}

	public Satker(Direktorat direktorat, String name, String desc, Date updateDate, String updateBy, Date createDate,
			String createBy) {
		this.direktorat = direktorat;
		this.name = name;
		this.desc = desc;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.createDate = createDate;
		this.createBy = createBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_satker", unique = true, nullable = false)
	public Integer getIdSatker() {
		return this.idSatker;
	}

	public void setIdSatker(Integer idSatker) {
		this.idSatker = idSatker;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_direktorat", nullable = false)
	public Direktorat getDirektorat() {
		return this.direktorat;
	}

	public void setDirektorat(Direktorat direktorat) {
		this.direktorat = direktorat;
	}

	@Column(name = "name", unique = true, nullable = false, length = 1000)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "desc", length = 1000)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "update_by", nullable = false, length = 45)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "create_by", nullable = false, length = 45)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

}
