package com.apps.pu.hibah.entity;
// Generated 08-Apr-2018 13:14:55 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transaksi generated by hbm2java
 */
@Entity
@Table(name = "transaksi", catalog = "hibah")
public class Transaksi implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idTransaksi;
	private int idSatker;
	private int idBarang;
	private Integer nup;
	private String penerima;
	private String lokasi;
	private String tahunAnggaran;
	private Long nilaiPerolehan;
	private String persetujuanPmk;
	private String persetujuanKemenkeu;
	private String skPenetapanHibah;
	private String bast;
	private String skPenghapusan;
	private Date updateDate;
	private String updateBy;
	private Date createDate;
	private String createBy;

	public Transaksi() {
	}

	public Transaksi(int idSatker, int idBarang, String penerima, Date updateDate, String updateBy, Date createDate,
			String createBy) {
		this.idSatker = idSatker;
		this.idBarang = idBarang;
		this.penerima = penerima;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.createDate = createDate;
		this.createBy = createBy;
	}

	public Transaksi(int idSatker, int idBarang, Integer nup, String penerima, String lokasi, String tahunAnggaran,
			Long nilaiPerolehan, String persetujuanPmk, String persetujuanKemenkeu, String skPenetapanHibah,
			String bast, String skPenghapusan, Date updateDate, String updateBy, Date createDate, String createBy) {
		this.idSatker = idSatker;
		this.idBarang = idBarang;
		this.nup = nup;
		this.penerima = penerima;
		this.lokasi = lokasi;
		this.tahunAnggaran = tahunAnggaran;
		this.nilaiPerolehan = nilaiPerolehan;
		this.persetujuanPmk = persetujuanPmk;
		this.persetujuanKemenkeu = persetujuanKemenkeu;
		this.skPenetapanHibah = skPenetapanHibah;
		this.bast = bast;
		this.skPenghapusan = skPenghapusan;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.createDate = createDate;
		this.createBy = createBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_transaksi", unique = true, nullable = false)
	public Integer getIdTransaksi() {
		return this.idTransaksi;
	}

	public void setIdTransaksi(Integer idTransaksi) {
		this.idTransaksi = idTransaksi;
	}

	@Column(name = "id_satker", nullable = false)
	public int getIdSatker() {
		return this.idSatker;
	}

	public void setIdSatker(int idSatker) {
		this.idSatker = idSatker;
	}

	@Column(name = "id_barang", nullable = false)
	public int getIdBarang() {
		return this.idBarang;
	}

	public void setIdBarang(int idBarang) {
		this.idBarang = idBarang;
	}

	@Column(name = "nup")
	public Integer getNup() {
		return this.nup;
	}

	public void setNup(Integer nup) {
		this.nup = nup;
	}

	@Column(name = "penerima", nullable = false, length = 2000)
	public String getPenerima() {
		return this.penerima;
	}

	public void setPenerima(String penerima) {
		this.penerima = penerima;
	}

	@Column(name = "lokasi", length = 2000)
	public String getLokasi() {
		return this.lokasi;
	}

	public void setLokasi(String lokasi) {
		this.lokasi = lokasi;
	}

	@Column(name = "tahun_anggaran", length = 45)
	public String getTahunAnggaran() {
		return this.tahunAnggaran;
	}

	public void setTahunAnggaran(String tahunAnggaran) {
		this.tahunAnggaran = tahunAnggaran;
	}

	@Column(name = "nilai_perolehan")
	public Long getNilaiPerolehan() {
		return this.nilaiPerolehan;
	}

	public void setNilaiPerolehan(Long nilaiPerolehan) {
		this.nilaiPerolehan = nilaiPerolehan;
	}

	@Column(name = "persetujuan_pmk", length = 500)
	public String getPersetujuanPmk() {
		return this.persetujuanPmk;
	}

	public void setPersetujuanPmk(String persetujuanPmk) {
		this.persetujuanPmk = persetujuanPmk;
	}

	@Column(name = "persetujuan_kemenkeu", length = 500)
	public String getPersetujuanKemenkeu() {
		return this.persetujuanKemenkeu;
	}

	public void setPersetujuanKemenkeu(String persetujuanKemenkeu) {
		this.persetujuanKemenkeu = persetujuanKemenkeu;
	}

	@Column(name = "sk_penetapan_hibah", length = 500)
	public String getSkPenetapanHibah() {
		return this.skPenetapanHibah;
	}

	public void setSkPenetapanHibah(String skPenetapanHibah) {
		this.skPenetapanHibah = skPenetapanHibah;
	}

	@Column(name = "bast", length = 500)
	public String getBast() {
		return this.bast;
	}

	public void setBast(String bast) {
		this.bast = bast;
	}

	@Column(name = "sk_penghapusan", length = 500)
	public String getSkPenghapusan() {
		return this.skPenghapusan;
	}

	public void setSkPenghapusan(String skPenghapusan) {
		this.skPenghapusan = skPenghapusan;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "update_by", nullable = false, length = 45)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "create_by", nullable = false, length = 45)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

}
